### ISSUE TITLE
Flat =0 and RED =0 in Figure.png

### ISSUE THREAD

**Issue by MG-ng** [marinlauber/Python-VPP#29]
Is it intentional that the flattening factor `Flat` and the depowering factor `RED` are = 0 in the generated polar graph which you can see here? 

![Figure](https://github.com/marinlauber/Python-VPP/assets/45321071/db46ac67-1e4b-4ad0-89a6-7028297ce7af)

I've generated it by setting n=5 the line `vpp.polar(5, True)` in `runVPP.py` on the current branch master. 

In the ORC PDF is written that `Flat = 1` in the full power condition (original camber) and `RED = 2` normally (no reefed sail).

**Comment by marinlauber** [comment]
If I remember correctly, they are not set in the store array, https://github.com/marinlauber/Python-VPP/blob/2fd978da46cfe58fb412ba127ea20e551d08a17a/src/VPPMod.py#L256C21-L256C114
so they take the default value of 0. 
This is because the main optimization loop doesn't have yet a way to also optimize for these constraints, only the dev branch, which is unstable.

**Comment by MG-ng** [comment]
Okay, thank you very much! 
I look forward to the merge of the dev branch then.
